### ISSUE TITLE
Input stylesheet does not reflect its current state

### ISSUE THREAD

**Issue by ReprimandedKaito** [ReprimandedKaito/matchmatcher-local#2]
Qt elements don't automatically apply the correct style rule when their attributes change.

![image](https://github.com/ReprimandedKaito/matchmatcher-local/assets/116013630/5ed9d675-266a-4c05-b1a7-cea4e4b8c392)

Given the following stylesheet, if `region` input (`QLineEdit`) is initially read-only, it will not be editable and will be gray.
However, after it becomes non-read-only, the text will be editable but still has the color gray.

```css
/* SEE https://stackoverflow.com/a/23995247 */

/*
QLineEdit[readOnly="false"] {
  color: black;
  background-color: white;
}
*/

QLineEdit[readOnly="true"] {
  color: #808080;
  background-color: #F0F0F0;
}
```

Maybe this is the reason:

> ## Limitations
> There are limitations to using this trick. The main one is that the style will not update itself automatically when the value of a property referenced from the style sheet changes.
> https://wiki.qt.io/Dynamic_Properties_and_Stylesheets

---

Note: Also, AFAIK, we are using Qt 5 (https://doc.qt.io/qt-5/stylesheet-reference.html).
